steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/nivaran/frontend:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/nivaran/frontend:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nivaran-frontend'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/nivaran/frontend:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=80'
      - '--memory=256Mi'
      - '--cpu=1'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/nivaran/frontend:latest'
