export const states = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand',
  'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
  'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
  'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura',
  'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  'Delhi', 'Chandigarh',
];

export const citiesByState = {
  'Andhra Pradesh': ['Visakhapatnam', 'Vijayawada', 'Guntur', 'Nellore', 'Kurnool', 'Rajahmundry', 'Tirupati', 'Kakinada'],
  'Arunachal Pradesh': ['Itanagar', 'Naharlagun', 'Pasighat', 'Tawang'],
  'Assam': ['Guwahati', 'Silchar', 'Dibrugarh', 'Jorhat', 'Nagaon', 'Tinsukia', 'Tezpur'],
  'Bihar': ['Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Purnia', 'Darbhanga', 'Bihar Sharif'],
  'Chhattisgarh': ['Raipur', 'Bhilai', 'Bilaspur', 'Korba', 'Durg', 'Rajnandgaon'],
  'Goa': ['Panaji', 'Margao', 'Vasco da Gama', 'Mapusa', 'Ponda'],
  'Gujarat': ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar', 'Jamnagar', 'Junagadh', 'Gandhinagar', 'Anand'],
  'Haryana': ['Chandigarh', 'Faridabad', 'Gurugram', 'Panipat', 'Ambala', 'Karnal', 'Sonipat', 'Hisar'],
  'Himachal Pradesh': ['Shimla', 'Dharamshala', 'Mandi', 'Solan', 'Kullu', 'Manali'],
  'Jharkhand': ['Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Deoghar', 'Hazaribagh'],
  'Karnataka': ['Bengaluru', 'Mysuru', 'Hubli', 'Mangaluru', 'Belagavi', 'Davangere', 'Bellary', 'Shivamogga'],
  'Kerala': ['Thiruvananthapuram', 'Kochi', 'Kozhikode', 'Thrissur', 'Alappuzha', 'Kollam', 'Palakkad', 'Kannur'],
  'Madhya Pradesh': ['Bhopal', 'Indore', 'Jabalpur', 'Gwalior', 'Ujjain', 'Sagar', 'Dewas', 'Satna'],
  'Maharashtra': ['Mumbai', 'Pune', 'Nagpur', 'Thane', 'Nashik', 'Aurangabad', 'Solapur', 'Kolhapur', 'Amravati'],
  'Manipur': ['Imphal', 'Bishnupur', 'Churachandpur', 'Thoubal'],
  'Meghalaya': ['Shillong', 'Tura', 'Nongstoin', 'Jowai'],
  'Mizoram': ['Aizawl', 'Lunglei', 'Champhai', 'Serchhip'],
  'Nagaland': ['Kohima', 'Dimapur', 'Mokokchung', 'Tuensang'],
  'Odisha': ['Bhubaneswar', 'Cuttack', 'Rourkela', 'Berhampur', 'Sambalpur', 'Puri', 'Balasore'],
  'Punjab': ['Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Bathinda', 'Mohali', 'Hoshiarpur'],
  'Rajasthan': ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota', 'Bikaner', 'Ajmer', 'Bhilwara', 'Alwar'],
  'Sikkim': ['Gangtok', 'Namchi', 'Mangan', 'Gyalshing'],
  'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem', 'Tirunelveli', 'Vellore', 'Erode'],
  'Telangana': ['Hyderabad', 'Warangal', 'Nizamabad', 'Karimnagar', 'Ramagundam', 'Khammam'],
  'Tripura': ['Agartala', 'Udaipur', 'Dharmanagar', 'Kailashahar'],
  'Uttar Pradesh': ['Lucknow', 'Kanpur', 'Agra', 'Varanasi', 'Prayagraj', 'Ghaziabad', 'Noida', 'Meerut', 'Bareilly'],
  'Uttarakhand': ['Dehradun', 'Haridwar', 'Rishikesh', 'Haldwani', 'Roorkee', 'Nainital'],
  'West Bengal': ['Kolkata', 'Howrah', 'Durgapur', 'Asansol', 'Siliguri', 'Bardhaman', 'Malda', 'Darjeeling'],
  'Delhi': ['New Delhi', 'Dwarka', 'Rohini', 'Saket', 'Karol Bagh', 'Lajpat Nagar', 'Connaught Place', 'Hauz Khas'],
  'Chandigarh': ['Chandigarh'],
};

export const areasByCity = {
  'Mumbai': ['Andheri', 'Borivali', 'Dadar', 'Bandra', 'Malad', 'Thane West', 'Navi Mumbai', 'Kurla', 'Powai', 'Worli'],
  'Delhi': ['Connaught Place', 'Hauz Khas', 'Lajpat Nagar', 'Karol Bagh', 'Rohini', 'Dwarka', 'Saket', 'Vasant Kunj', 'Pitampura'],
  'New Delhi': ['India Gate', 'Chanakyapuri', 'Lutyens Delhi', 'Sarojini Nagar', 'Khan Market'],
  'Bengaluru': ['Koramangala', 'Indiranagar', 'Whitefield', 'Jayanagar', 'MG Road', 'Marathahalli', 'Electronic City', 'BTM Layout'],
  'Hyderabad': ['HITEC City', 'Gachibowli', 'Madhapur', 'Kukatpally', 'Secunderabad', 'Banjara Hills', 'Jubilee Hills'],
  'Chennai': ['T Nagar', 'Velachery', 'Adyar', 'Anna Nagar', 'Guindy', 'Porur', 'Thoraipakkam', 'OMR'],
  'Kolkata': ['Salt Lake', 'New Town', 'Park Street', 'Ballygunge', 'Dum Dum', 'Howrah', 'Barasat'],
  'Pune': ['Kothrud', 'Hinjewadi', 'Shivajinagar', 'Baner', 'Viman Nagar', 'Hadapsar', 'Pimpri'],
  'Ahmedabad': ['Navrangpura', 'SG Highway', 'Satellite', 'Bodakdev', 'Vastrapur', 'Maninagar', 'Paldi'],
  'Jaipur': ['Vaishali Nagar', 'Mansarovar', 'Malviya Nagar', 'C Scheme', 'Sodala', 'Bani Park', 'Tonk Road'],
  'Lucknow': ['Gomti Nagar', 'Hazratganj', 'Aliganj', 'Indira Nagar', 'Aminabad', 'Mahanagar'],
  'Surat': ['Adajan', 'Vesu', 'Althan', 'Katargam', 'Varachha', 'Udhna'],
  'Patna': ['Kankarbagh', 'Boring Road', 'Patliputra', 'Rajendra Nagar', 'Fraser Road', 'Bailey Road'],
  'Bhopal': ['MP Nagar', 'Arera Colony', 'New Market', 'Hoshangabad Road', 'Kolar Road', 'Shahpura'],
  'Indore': ['Vijay Nagar', 'Scheme 140', 'Palasia', 'MG Road', 'Rajendra Nagar', 'Bhawarkua'],
  'Chandigarh': ['Sector 17', 'Sector 22', 'Sector 35', 'Sector 44', 'Sector 8', 'Industrial Area Phase 1'],
  'Guwahati': ['Uzan Bazar', 'Beltola', 'Dispur', 'Panbazar', 'Six Mile', 'Zoo Road', 'Maligaon'],
  'Thiruvananthapuram': ['Kowdiar', 'Kazhakootam', 'Nanthancode', 'Poojappura', 'Sreekaryam', 'Ulloor'],
  'Kochi': ['Edapally', 'Kakkanad', 'Marine Drive', 'Fort Kochi', 'Panampilly Nagar', 'Vyttila'],
  'Coimbatore': ['RS Puram', 'Race Course', 'Gandhipuram', 'Peelamedu', 'Saravanampatti', 'Kovaipudur'],
  'Visakhapatnam': ['Madhurawada', 'Gajuwaka', 'MVP Colony', 'Dwaraka Nagar', 'Pendurthi', 'Seethammadhara'],
  'Nagpur': ['Dharampeth', 'Mahal', 'Sadar', 'Nandanvan', 'Manish Nagar', 'Hingna'],
  'Agra': ['Tajganj', 'Kamla Nagar', 'Dayalbagh', 'Sikandra', 'Loha Mandi', 'Shahganj'],
  'Varanasi': ['Lanka', 'Assi', 'Sigra', 'Cantonment', 'Bhelupur', 'Pandeypur'],
  'Prayagraj': ['Civil Lines', 'Katra', 'George Town', 'Tagore Town', 'Naini', 'Ashok Nagar'],
  'Noida': ['Sector 62', 'Sector 18', 'Sector 15', 'Sector 44', 'Sector 128', 'Sector 137'],
  'Gurugram': ['DLF Phase 1', 'DLF Phase 2', 'Sector 14', 'MG Road', 'Sohna Road', 'Sector 56'],
  'Faridabad': ['Sector 15', 'Sector 16', 'Sector 29', 'DLF Faridabad', 'Neelam Flyover', 'Badarpur'],
  'Ghaziabad': ['Raj Nagar', 'Kavi Nagar', 'Indirapuram', 'Shipra Sun City', 'Vaishali', 'Crossing Republik'],
  'Thane': ['Thane West', 'Thane East', 'Naupada', 'Vartak Nagar', 'Manpada', 'Kopri'],
};

export const pincodesByArea = {
  'Andheri': '400093', 'Borivali': '400092', 'Dadar': '400014', 'Bandra': '400050', 'Malad': '400064', 'Powai': '400076', 'Worli': '400030', 'Kurla': '400070', 'Navi Mumbai': '400614', 'Thane West': '400602',
  'Connaught Place': '110001', 'Hauz Khas': '110016', 'Lajpat Nagar': '110024', 'Karol Bagh': '110005', 'Rohini': '110085', 'Dwarka': '110075', 'Saket': '110017', 'Vasant Kunj': '110070',
  'India Gate': '110001', 'Chanakyapuri': '110021', 'Khan Market': '110003',
  'Koramangala': '560034', 'Indiranagar': '560038', 'Whitefield': '560066', 'Jayanagar': '560011', 'MG Road': '560001', 'Marathahalli': '560037', 'Electronic City': '560100', 'BTM Layout': '560029',
  'HITEC City': '500081', 'Gachibowli': '500032', 'Madhapur': '500081', 'Kukatpally': '500072', 'Banjara Hills': '500034', 'Jubilee Hills': '500033', 'Secunderabad': '500003',
  'T Nagar': '600017', 'Velachery': '600042', 'Adyar': '600020', 'Anna Nagar': '600040', 'Guindy': '600032', 'Porur': '600116', 'OMR': '603103', 'Thoraipakkam': '600097',
  'Salt Lake': '700091', 'New Town': '700156', 'Park Street': '700016', 'Ballygunge': '700019', 'Howrah': '711101',
  'Kothrud': '411038', 'Hinjewadi': '411057', 'Shivajinagar': '411005', 'Baner': '411045', 'Viman Nagar': '411014', 'Hadapsar': '411028', 'Pimpri': '411018',
  'Navrangpura': '380009', 'SG Highway': '380054', 'Satellite': '380015', 'Vastrapur': '380015', 'Maninagar': '380008',
  'Vaishali Nagar': '302021', 'Mansarovar': '302020', 'Malviya Nagar': '302017', 'C Scheme': '302001', 'Bani Park': '302016',
  'Gomti Nagar': '226010', 'Hazratganj': '226001', 'Indira Nagar': '226016', 'Aliganj': '226024',
  'Adajan': '395009', 'Vesu': '395007', 'Katargam': '395004', 'Varachha': '395006',
  'Kankarbagh': '800020', 'Boring Road': '800013', 'Patliputra': '800013', 'Rajendra Nagar': '800016',
  'MP Nagar': '462011', 'Arera Colony': '462016', 'Shahpura': '462039', 'Kolar Road': '462042',
  'Vijay Nagar': '452010', 'Palasia': '452001', 'MG Road': '452001', 'Rajendra Nagar': '452012',
  'Sector 17': '160017', 'Sector 22': '160022', 'Sector 35': '160035', 'Sector 44': '160044',
  'Uzan Bazar': '781001', 'Dispur': '781006', 'Beltola': '781028', 'Six Mile': '781022',
  'Kowdiar': '695003', 'Kazhakootam': '695582', 'Nanthancode': '695003',
  'Edapally': '682024', 'Kakkanad': '682030', 'Marine Drive': '682031', 'Fort Kochi': '682001',
  'RS Puram': '641002', 'Race Course': '641018', 'Gandhipuram': '641012',
  'Madhurawada': '530041', 'MVP Colony': '530017', 'Dwaraka Nagar': '530016',
  'Dharampeth': '440010', 'Mahal': '440032', 'Manish Nagar': '440015',
  'Tajganj': '282001', 'Kamla Nagar': '282005', 'Dayalbagh': '282005',
  'Lanka': '221005', 'Assi': '221005', 'Sigra': '221010', 'Bhelupur': '221005',
  'Civil Lines': '211001', 'Katra': '211002', 'Naini': '211008',
  'Sector 62': '201301', 'Sector 18': '201301', 'Sector 44': '201301', 'Sector 128': '201304',
  'DLF Phase 1': '122002', 'Sector 14': '122001', 'MG Road': '122002',
  'Sector 15': '121007', 'Sector 29': '121008',
  'Raj Nagar': '201001', 'Kavi Nagar': '201002', 'Indirapuram': '201014',
  'Thane West': '400602', 'Thane East': '400603', 'Naupada': '400602',
  'Dwarka': '110075', 'Saket': '110017', 'Vasant Kunj': '110070', 'Pitampura': '110034',
};
