const en = {
  translation: {
    app: { name: 'Nivaran', tagline: 'Civic Grievance Platform', subtitle: 'Empowering communities through technology' },
    nav: { home: 'Home', dashboard: 'Dashboard', report: 'Report Issue', leaderboard: 'Leaderboard', myReports: 'My Reports', profile: 'Profile', login: 'Login', signup: 'Sign Up', logout: 'Logout', admin: 'Admin Panel', tracking: 'Complaint Tracking', about: 'About', impact: 'Impact', awareness: 'Awareness', signIn: 'Sign In', getStarted: 'Get Started' },
    hero: { badge: 'Hyperlocal Civic Platform', title1: 'Empower Your', title2: 'Neighborhood', subtitle: 'Report civic issues, track resolutions, and build a stronger community — one report at a time.', goDashboard: 'Go to Dashboard', getStarted: 'Get Started', signIn: 'Sign In', community: 'issues resolved by the community', card1: 'Pothole Report', card1loc: 'Main Street', card2: 'Resolved', card2detail: 'Streetlight fixed', card3: 'In Progress', card3detail: 'Drain cleaning', cardBadge: '98%' },
    about: { badge: 'About Nivaran', title1: 'Your Voice, Your Neighborhood,', title2: 'Your Impact', subtitle: 'Nivaran bridges the gap between citizens and civic authorities, making issue reporting transparent, trackable, and community-driven.', feature1Title: 'Geo-Tagged Reports', feature1Desc: 'Pinpoint issues on an interactive map so authorities know exactly where help is needed.', feature2Title: 'Track Resolution', feature2Desc: 'Follow your reports from submission to resolution with real-time status updates.', feature3Title: 'Community Powered', feature3Desc: 'Upvote issues, earn badges, and build a visible impact score in your neighborhood.', feature4Title: 'AI-Assisted Reporting', feature4Desc: 'Upload a photo and let AI suggest the category and description for faster reporting.' },
    impact: { badge: 'Community Impact', title1: 'Making Cities Better,', title2: 'Together', subtitle: 'Every report filed is a step toward cleaner, safer, and more sustainable neighborhoods.', stat1Label: 'Issues Resolved', stat2Label: 'Resolution Rate', stat3Label: 'Cities Active', stat4Label: 'Community Members', footer: 'Powered by community effort and civic collaboration' },
    awareness: { badge: 'How It Works', title1: 'Report an Issue in', title2: '4 Simple Steps', subtitle: 'From noticing a problem to seeing it resolved — Nivaran makes civic engagement effortless.', step1Title: '1. Snap a Photo', step1Desc: 'Take a picture of the civic issue you want to report.', step2Title: '2. Pin the Location', step2Desc: 'Drop a pin on the map so authorities can find it easily.', step3Title: '3. Add Details', step3Desc: 'Describe the issue — AI helps suggest a category and summary.', step4Title: '4. Track Progress', step4Desc: 'Monitor your report status and upvote others to build impact.', cta: 'Start Making a Difference' },
    footer: { description: 'Hyperlocal civic issue reporting and awareness platform. Empowering communities to build better neighborhoods.', quickLinks: 'Quick Links', contact: 'Contact', followUs: 'Follow Us', builtWith: 'Built with', forCommunities: 'for stronger communities.', copyright: 'All rights reserved.', about: 'About', impact: 'Impact', awareness: 'Awareness', leaderboard: 'Leaderboard', signIn: 'Sign In', getStarted: 'Get Started' },
    dashboard: { welcome: 'Welcome back', feedView: 'Feed View', mapView: 'Map View', noReports: 'No reports yet. Be the first to report an issue!', totalReports: 'Total Reports', resolved: 'Resolved', inProgress: 'In Progress', resolutionRate: 'Resolution Rate', filters: 'Filters & Sort' },
    report: { title: 'Report an Issue', subtitle: 'Help your community by reporting civic issues in your area.', photo: 'Photo', location: 'Location', details: 'Details', submit: 'Submit', uploadPhoto: 'Upload a Photo', photoDesc: 'Take a clear photo of the issue. AI will analyze it to suggest details.', clickToUpload: 'Click to upload or drag and drop', skipPhoto: 'Skip, no photo', selectLocation: 'Select Location', locationDesc: 'Choose your location using the dropdowns or pin it on the map.', state: 'State', city: 'City', area: 'Area / Locality', pincode: 'Pincode', addDetails: 'Add Details', description: 'Description', category: 'Category', review: 'Review & Submit', reviewDesc: 'Please review your report before submitting.', submitReport: 'Submit Report', submitting: 'Submitting...', uploading: 'Uploading image...', aiAnalyzing: 'AI is analyzing your image...', aiSuggestions: 'AI suggestions applied — feel free to edit.' },
    status: { pending: 'Pending', verified: 'Verified', assigned: 'Assigned', inProgress: 'In Progress', resolved: 'Resolved', justNow: 'Just now' },
    tracking: { title: 'Complaint Tracking', subtitle: 'Track the real-time status of your complaint', complaintId: 'Complaint ID', currentStatus: 'Current Status', lastUpdated: 'Last Updated', timeline: 'Progress Timeline' },
    admin: { title: 'Admin Dashboard', totalComplaints: 'Total Complaints', resolvedComplaints: 'Resolved Complaints', pendingComplaints: 'Pending Complaints', departmentStats: 'Department Statistics', trends: 'Trends', userActivity: 'User Activity', search: 'Search complaints...', manage: 'Manage Complaints', assign: 'Assign', darkMode: 'Dark Mode' },
    voice: { title: 'Voice Report', subtitle: 'Speak your complaint in Hindi or English', startRecording: 'Start Recording', stopRecording: 'Stop Recording', recording: 'Recording...', preview: 'Preview', language: 'Language', hindi: 'Hindi', english: 'English', tapToSpeak: 'Tap to speak your complaint' },
    common: { loading: 'Loading...', error: 'Something went wrong', retry: 'Retry', save: 'Save', cancel: 'Cancel', delete: 'Delete', confirm: 'Confirm', search: 'Search', noData: 'No data available', viewAll: 'View All', seeMore: 'See More', anonymous: 'Anonymous' },
    nearby: { title: 'Nearby Issues', alert: 'There are active issues near your area', view: 'View on Map' },
    auth: { welcomeBack: 'Welcome Back', signInSub: 'Sign in to continue making an impact', email: 'Email', password: 'Password', emailPlaceholder: 'you@example.com', passwordPlaceholder: '••••••••', signIn: 'Sign In', orContinue: 'or continue with', signInGoogle: 'Sign in with Google', noAccount: 'Don\'t have an account?', signUp: 'Sign up', join: 'Join Nivaran', signUpSub: 'Start making your neighborhood better', fullName: 'Full Name', namePlaceholder: 'Your name', passwordMinPlaceholder: 'Minimum 6 characters', createAccount: 'Create Account', signUpGoogle: 'Sign up with Google', hasAccount: 'Already have an account?', passwordMinError: 'Password must be at least 6 characters', welcomeToast: 'Welcome back to Nivaran!', googleSignInToast: 'Signed in with Google!', welcomeToastSignup: 'Welcome to Nivaran!', emailExists: 'is already registered. Sign in with your email and password instead.', emailExistsSignup: 'is already registered. Please sign in instead.' },
    pdf: { generate: 'Generate PDF Report', downloading: 'Downloading...' },
  },
};

export default en;
