const hi = {
  translation: {
    app: { name: 'निवारण', tagline: 'नागरिक शिकायत मंच', subtitle: 'प्रौद्योगिकी के माध्यम से समुदायों को सशक्त बनाना' },
    nav: { home: 'होम', dashboard: 'डैशबोर्ड', report: 'शिकायत दर्ज करें', leaderboard: 'लीडरबोर्ड', myReports: 'मेरी शिकायतें', profile: 'प्रोफाइल', login: 'लॉग इन', signup: 'साइन अप', logout: 'लॉग आउट', admin: 'एडमिन पैनल', tracking: 'शिकायत ट्रैकिंग', about: 'हमारे बारे में', impact: 'प्रभाव', awareness: 'जागरूकता', signIn: 'साइन इन', getStarted: 'शुरू करें' },
    hero: { badge: 'हाइपरलोकल नागरिक मंच', title1: 'अपने', title2: 'पड़ोस को सशक्त बनाएं', subtitle: 'नागरिक समस्याओं की रिपोर्ट करें, समाधान ट्रैक करें, और एक मजबूत समुदाय बनाएं — एक रिपोर्ट एक बार में।', goDashboard: 'डैशबोर्ड पर जाएं', getStarted: 'शुरू करें', signIn: 'साइन इन', community: 'समुदाय द्वारा हल की गई समस्याएं', card1: 'गड्ढा रिपोर्ट', card1loc: 'मुख्य सड़क', card2: 'हल हुआ', card2detail: 'स्ट्रीटलाइट ठीक हुई', card3: 'प्रगति पर', card3detail: 'नाली की सफाई', cardBadge: '९८%' },
    about: { badge: 'निवारण के बारे में', title1: 'आपकी आवाज, आपका पड़ोस,', title2: 'आपका प्रभाव', subtitle: 'निवारण नागरिकों और प्रशासन के बीच की खाई को पाटता है, जिससे समस्या रिपोर्टिंग पारदर्शी, ट्रैक करने योग्य और समुदाय-संचालित बनती है।', feature1Title: 'जियो-टैग्ड रिपोर्ट', feature1Desc: 'इंटरैक्टिव मैप पर समस्याओं को पिनपॉइंट करें ताकि अधिकारियों को पता चले कि कहां मदद की जरूरत है।', feature2Title: 'समाधान ट्रैक करें', feature2Desc: 'रियल-टाइम स्टेटस अपडेट के साथ अपनी रिपोर्ट को सबमिशन से समाधान तक फॉलो करें।', feature3Title: 'समुदाय संचालित', feature3Desc: 'समस्याओं को अपवोट करें, बैज अर्जित करें, और अपने पड़ोस में एक दृश्य प्रभाव स्कोर बनाएं।', feature4Title: 'AI-सहायता प्राप्त रिपोर्टिंग', feature4Desc: 'एक फोटो अपलोड करें और AI को तेज रिपोर्टिंग के लिए श्रेणी और विवरण सुझाने दें।' },
    impact: { badge: 'सामुदायिक प्रभाव', title1: 'शहरों को बेहतर बनाना,', title2: 'एक साथ', subtitle: 'हर रिपोर्ट स्वच्छ, सुरक्षित और अधिक टिकाऊ पड़ोस की ओर एक कदम है।', stat1Label: 'समस्याएं हल हुईं', stat2Label: 'समाधान दर', stat3Label: 'सक्रिय शहर', stat4Label: 'समुदाय के सदस्य', footer: 'सामुदायिक प्रयास और नागरिक सहयोग द्वारा संचालित' },
    awareness: { badge: 'यह कैसे काम करता है', title1: 'रिपोर्ट करें', title2: '4 सरल चरणों में', subtitle: 'समस्या देखने से लेकर उसके समाधान तक — निवारण नागरिक जुड़ाव को सरल बनाता है।', step1Title: '१. फोटो लें', step1Desc: 'जिस नागरिक समस्या की रिपोर्ट करना चाहते हैं उसकी तस्वीर लें।', step2Title: '२. स्थान पिन करें', step2Desc: 'मैप पर पिन ड्रॉप करें ताकि अधिकारी इसे आसानी से ढूंढ सकें।', step3Title: '३. विवरण जोड़ें', step3Desc: 'समस्या का वर्णन करें — AI श्रेणी और सारांश सुझाने में मदद करता है।', step4Title: '४. प्रगति ट्रैक करें', step4Desc: 'अपनी रिपोर्ट की स्थिति देखें और प्रभाव बनाने के लिए दूसरों को अपवोट करें।', cta: 'बदलाव लाना शुरू करें' },
    footer: { description: 'हाइपरलोकल नागरिक समस्या रिपोर्टिंग और जागरूकता मंच। बेहतर पड़ोस बनाने के लिए समुदायों को सशक्त बनाना।', quickLinks: 'त्वरित लिंक', contact: 'संपर्क', followUs: 'हमें फॉलो करें', builtWith: 'के साथ बनाया गया', forCommunities: 'मजबूत समुदायों के लिए।', copyright: 'सर्वाधिकार सुरक्षित।', about: 'हमारे बारे में', impact: 'प्रभाव', awareness: 'जागरूकता', leaderboard: 'लीडरबोर्ड', signIn: 'साइन इन', getStarted: 'शुरू करें' },
    dashboard: { welcome: 'वापसी पर स्वागत है', feedView: 'फीड व्यू', mapView: 'मैप व्यू', noReports: 'अभी तक कोई रिपोर्ट नहीं। पहली समस्या की रिपोर्ट करने वाले बनें!', totalReports: 'कुल रिपोर्ट', resolved: 'हल हुई', inProgress: 'प्रगति पर', resolutionRate: 'समाधान दर', filters: 'फ़िल्टर और सॉर्ट' },
    report: { title: 'समस्या की रिपोर्ट करें', subtitle: 'अपने क्षेत्र में नागरिक समस्याओं की रिपोर्ट करके समुदाय की मदद करें।', photo: 'फोटो', location: 'स्थान', details: 'विवरण', submit: 'जमा करें', uploadPhoto: 'फोटो अपलोड करें', photoDesc: 'समस्या की स्पष्ट फोटो लें। AI आपकी फोटो का विश्लेषण कर विवरण सुझाएगा।', clickToUpload: 'अपलोड करने के लिए क्लिक करें', skipPhoto: 'छोड़ें, फोटो नहीं', selectLocation: 'स्थान चुनें', locationDesc: 'ड्रॉपडाउन का उपयोग करके या मैप पर पिन करके स्थान चुनें।', state: 'राज्य', city: 'शहर', area: 'क्षेत्र / इलाका', pincode: 'पिनकोड', addDetails: 'विवरण जोड़ें', description: 'विवरण', category: 'श्रेणी', review: 'समीक्षा करें और जमा करें', reviewDesc: 'कृपया जमा करने से पहले अपनी रिपोर्ट की समीक्षा करें।', submitReport: 'रिपोर्ट जमा करें', submitting: 'जमा हो रहा है...', uploading: 'इमेज अपलोड हो रही है...', aiAnalyzing: 'AI आपकी इमेज का विश्लेषण कर रहा है...', aiSuggestions: 'AI सुझाव लागू किए गए — संपादित करने के लिए स्वतंत्र हैं।' },
    status: { pending: 'लंबित', verified: 'सत्यापित', assigned: 'आवंटित', inProgress: 'प्रगति पर', resolved: 'हल हुआ', justNow: 'अभी अभी' },
    tracking: { title: 'शिकायत ट्रैकिंग', subtitle: 'अपनी शिकायत की रियल-टाइम स्थिति ट्रैक करें', complaintId: 'शिकायत आईडी', currentStatus: 'वर्तमान स्थिति', lastUpdated: 'अंतिम अपडेट', timeline: 'प्रगति समयरेखा' },
    admin: { title: 'एडमिन डैशबोर्ड', totalComplaints: 'कुल शिकायतें', resolvedComplaints: 'हल की गई शिकायतें', pendingComplaints: 'लंबित शिकायतें', departmentStats: 'विभागीय आंकड़े', trends: 'रुझान', userActivity: 'उपयोगकर्ता गतिविधि', search: 'शिकायतें खोजें...', manage: 'शिकायतों का प्रबंधन', assign: 'आवंटित करें', darkMode: 'डार्क मोड' },
    voice: { title: 'वॉइस रिपोर्ट', subtitle: 'हिंदी या अंग्रेजी में अपनी शिकायत बोलें', startRecording: 'रिकॉर्डिंग शुरू करें', stopRecording: 'रिकॉर्डिंग बंद करें', recording: 'रिकॉर्ड हो रहा है...', preview: 'पूर्वावलोकन', language: 'भाषा', hindi: 'हिंदी', english: 'अंग्रेजी', tapToSpeak: 'अपनी शिकायत बोलने के लिए टैप करें' },
    common: { loading: 'लोड हो रहा है...', error: 'कुछ गलत हो गया', retry: 'पुनः प्रयास करें', save: 'सहेजें', cancel: 'रद्द करें', delete: 'हटाएं', confirm: 'पुष्टि करें', search: 'खोजें', noData: 'कोई डेटा उपलब्ध नहीं', viewAll: 'सभी देखें', seeMore: 'और देखें', anonymous: 'गुमनाम' },
    nearby: { title: 'आस-पास की समस्याएं', alert: 'आपके क्षेत्र में सक्रिय समस्याएं हैं', view: 'मैप पर देखें' },
    auth: { welcomeBack: 'वापसी पर स्वागत है', signInSub: 'प्रभाव बनाना जारी रखने के लिए साइन इन करें', email: 'ईमेल', password: 'पासवर्ड', emailPlaceholder: 'you@example.com', passwordPlaceholder: '••••••••', signIn: 'साइन इन', orContinue: 'या इससे जारी रखें', signInGoogle: 'Google से साइन इन करें', noAccount: 'खाता नहीं है?', signUp: 'साइन अप', join: 'निवारण में शामिल हों', signUpSub: 'अपने पड़ोस को बेहतर बनाना शुरू करें', fullName: 'पूरा नाम', namePlaceholder: 'आपका नाम', passwordMinPlaceholder: 'न्यूनतम 6 अक्षर', createAccount: 'खाता बनाएं', signUpGoogle: 'Google से साइन अप करें', hasAccount: 'पहले से खाता है?', passwordMinError: 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए', welcomeToast: 'निवारण में वापसी पर स्वागत है!', googleSignInToast: 'Google से साइन इन किया गया!', welcomeToastSignup: 'निवारण में आपका स्वागत है!', emailExists: 'पहले से पंजीकृत है। कृपया अपने ईमेल और पासवर्ड से साइन इन करें।', emailExistsSignup: 'पहले से पंजीकृत है। कृपया साइन इन करें।' },
    pdf: { generate: 'पीडीएफ रिपोर्ट बनाएं', downloading: 'डाउनलोड हो रहा है...' },
  },
};

export default hi;
